#!/bin/bash
servers=( int-portweb01 int-portweb02 int-adminweb01 int-linbe01 )
for server in "${servers[@]}"
do
  scp ~/.ssh/id_olh_qa.pub $server:~/
  ssh $server "mkdir .ssh; mv id_olh_qa.pub .ssh/authorized_keys; chmod 700 .ssh; chmod 600 .ssh/authorized_keys"
  ssh $server
done
