#! /bin/bash
tmux -S /var/tmux/liveon send-keys -t liveon:3.1 C-c
tmux -S /var/tmux/liveon send-keys -t liveon:3.2 C-c

tmux -S /var/tmux/liveon send-keys -t entity:3.1 C-c
tmux -S /var/tmux/liveon send-keys -t entity:3.2 C-c

tmux -S /var/tmux/liveon kill-server