#! /bin/bash --login

  session="new"
  directory="metanoiaex"
  #port="3000"

  tmux -S /var/tmux/metanoia new-session -s $session -n editor -d
  tmux -S /var/tmux/metanoia send-keys -t $session "cd ~/git/$directory/" C-m
  tmux -S /var/tmux/metanoia send-keys -t $session "v" C-m
  tmux -S /var/tmux/metanoia new-window -n rspec -t $session
  tmux -S /var/tmux/metanoia split-window -h -t $session
  tmux -S /var/tmux/metanoia new-window -n app -t $session
  tmux -S /var/tmux/metanoia split-window -h -t $session
  tmux -S /var/tmux/metanoia send-keys -t $session:2.1 "cd ~/git/$directory" C-m
  tmux -S /var/tmux/metanoia send-keys -t $session:2.2 "cd ~/git/$directory/" C-m
  tmux -S /var/tmux/metanoia send-keys -t $session:3.1 "cd ~/git/$directory" c-m
  tmux -S /var/tmux/metanoia send-keys -t $session:3.1 "bundle exec rails s -p $port" c-m
  tmux -S /var/tmux/metanoia send-keys -t $session:3.2 "cd ~/git/$directory" C-m
  tmux -S /var/tmux/metanoia send-keys -t $session:3.2 "bundle exec rails c" C-m
  tmux -S /var/tmux/metanoia rename-window -t $session:2 rspec
  tmux -S /var/tmux/metanoia rename-window -t $session:3 app
  tmux -S /var/tmux/metanoia select-window -t $session:1

tmux -S /var/tmux/metanoia new-session -s ngrok -n console -d

chgrp tmuxers /var/tmux/metanoia
tmux -S /var/tmux/metanoia -2 attach -t new
